<?php

/**
 * @file
 *
 * Term Tree Selector module.
 */

 /**
  * Implements hook_theme().
  */
function term_tree_selector_theme($existing, $type, $theme, $path) {
  return array(
    'term_tree_selector' => array(
      'variables' => array(
        'vocabulary' => NULL,
        'root_label' => NULL,
        'leaf_label' => NULL,
        'leaf_level' => NULL,
        'submit_label' => NULL,
      ),
    ),
  );
}
